### ISSUE TITLE
swift3

### ISSUE THREAD

**Issue by shoheiyokoyama** [shoheiyokoyama/SYBlinkAnimationKit#1]

**Comment by kyzmitch** [comment]
Hi, what is the proper way to use that in swift 3 project? Do we need convert it?

**Comment by shoheiyokoyama** [comment]
@kyzmitch 
I finished to converting `Swift3`. so you don't have to convert it.
Please install version `0.3.1`.

**Comment by kyzmitch** [comment]
Thank you a lot
